<h1>For Testing Purposes

In [1]:
from preprocessing import preprocess_data

file_path = 'labeled_data.csv'
data = preprocess_data(file_path,'tweet')

data

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet,processed_text
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...,rt as a woman you shouldnt complain about clea...
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,rt boy dats cold tyga dwn bad for cuffin dat h...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,rt dawg rt you ever fuck a bitch and she start...
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...,rt she look like a tranny
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...,rt the shit you hear about me might be true or...
...,...,...,...,...,...,...,...,...
24778,25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...,yous a muthaf in lie right his tl is trash now...
24779,25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an...",youve gone and broke the wrong heart baby and ...
24780,25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...,young buck wanna eat dat nigguh like i aint fu...
24781,25295,6,0,6,0,1,youu got wild bitches tellin you lies,youu got wild bitches tellin you lies
24782,25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...,ruffled ntac eileen dahlia beautiful color com...

In [2]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.sentiment import SentimentIntensityAnalyzer
from preprocessing import preprocess_data  # Make sure this script is in your notebook directory or PYTHONPATH

# Load and preprocess the data
filepath = 'labeled_data.csv'  # Update this path
preprocessed_data = preprocess_data(filepath, 'tweet')  # Update 'tweet_text' to your actual text column name

# Assuming create_features is a function that you have defined in one of your scripts
from feature import create_features
features = create_features(preprocessed_data)

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/laetitia/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [3]:
features

,10,100,1000,10000,11,12,13,14,15,150,...,yuh,yung,yup,zebra,zebras,zero,zimmerman,zone,zoo,compound
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2755
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.5423
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.9460
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3612
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.6808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24778,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000
24779,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.8074
24780,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3612
24781,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.7717
24782,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5994

In [4]:
preprocessed_data

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet,processed_text,sentiments,compound
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...,rt as a woman you shouldnt complain about clea...,"{'neg': 0.0, 'neu': 0.9, 'pos': 0.1, 'compound...",0.2755
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,rt boy dats cold tyga dwn bad for cuffin dat h...,"{'neg': 0.2, 'neu': 0.8, 'pos': 0.0, 'compound...",-0.5423
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,rt dawg rt you ever fuck a bitch and she start...,"{'neg': 0.576, 'neu': 0.424, 'pos': 0.0, 'comp...",-0.9460
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...,rt she look like a tranny,"{'neg': 0.0, 'neu': 0.615, 'pos': 0.385, 'comp...",0.3612
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...,rt the shit you hear about me might be true or...,"{'neg': 0.245, 'neu': 0.662, 'pos': 0.093, 'co...",-0.6808
...,...,...,...,...,...,...,...,...,...,...
24778,25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...,yous a muthaf in lie right his tl is trash now...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
24779,25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an...",youve gone and broke the wrong heart baby and ...,"{'neg': 0.454, 'neu': 0.546, 'pos': 0.0, 'comp...",-0.8074
24780,25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...,young buck wanna eat dat nigguh like i aint fu...,"{'neg': 0.0, 'neu': 0.815, 'pos': 0.185, 'comp...",0.3612
24781,25295,6,0,6,0,1,youu got wild bitches tellin you lies,youu got wild bitches tellin you lies,"{'neg': 0.573, 'neu': 0.427, 'pos': 0.0, 'comp...",-0.7717
24782,25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...,ruffled ntac eileen dahlia beautiful color com...,"{'neg': 0.0, 'neu': 0.755, 'pos': 0.245, 'comp...",0.5994

In [7]:
from nltk.sentiment import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()

# Example text
text = preprocessed_data['processed_text'][2]
scores = sid.polarity_scores(text)
print(scores)

{'neg': 0.576, 'neu': 0.424, 'pos': 0.0, 'compound': -0.946}